import React from 'react'
import NavbarStyleOne from '@/components/_App/NavbarStyle'
import PageBannerStyle1 from '@/components/Common/PageBannerStyle1'
// import AppDownloadStyle2 from '@/components/Common/AppDownloadStyle2'
import FooterStyleOne from '@/components/_App/FooterStyle'
 
const PrivacyPolicy = () => {
    return (
        <>
            <NavbarStyleOne /> 

            <PageBannerStyle1 
                pageTitle="Privacy Policy"
                homePageUrl="/"
                homePageText="Home"
                activePageText="Privacy Policy"
            />

            <div className="privacy-policy-area ptb-100">
                <div className="container">
                    <div className="privacy-policy-content">
                        <h1>Privacy Policy</h1>
                        <p>This Privacy Policy is intended to inform you regarding the personal information that may be collected through Technocrat monk and how we use, share, and protect that information. By using this site, you agree to this Privacy Policy, and as such we strongly encourage our visitors to reach through this content regularly to stay informed of its contents and any changes. In the following policy, “we, us, and site” are used to refer to Technocrat Monk.</p>

                        <h4>Applicability of this Privacy Policy</h4>
                        <p>This Privacy Policy reflects the information that is collected and shared via technocratmonk.com. For other distribution channels (email, social media, etc.) different rules may apply.</p>
                        

                        <h4>Use of Information</h4>
                        <p>In efforts to better serve your needs, Technocrat Monk collects and stores personal information that you choose to voluntarily provide through our contact forms and other means of communication in which you provide your information. The information collected may include but is not limited to your name, email address, phone number, and resume. The website may also auto-collect information to improve your user experience including your IP address, browser type, operating system, referring URLs, and actions taken on the site. This information may be used to offer you an improved user experience, to improve our site to better serve your needs, or to send periodic emails that may be relevant to your needs, respond to inquiries, questions and/or other requests.<br/>

We value your information, and protect your privacy by utilizing this information only in a way that best benefits you. Technocrat Monk does not rent, sell, or share personal information about you with other people or non-affiliated companies without your explicit approval outside of the following purposes:</p>
                       

                        <h4>To provide products or services you’ve requested</h4>
                        <p>To provide the information to trusted entities who work on behalf of or with Technocrat Monk under strict confidentiality agreements in order to help us communicate with you regarding relevant offers from Technocrat Monk and our marketing partners. These companies do not have any independent right to further share or disseminate this information to respond to subpoenas, court orders, or legal process, or to establish or exercise our legal rights or defend against legal claims<br/>

To share the information in order to investigate, prevent, or take action against any illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, or as otherwise required by law<br/>

To transfer information about you if Technocrat Monk is acquired by or merged with another company</p>

                        <h4>Secured Information</h4>
                        <p>We adopt best industry standards for data collection, storage, processing practices and security measures to protect you against unauthorized access, alteration, disclosure or destruction of your personal information.</p>

                        <h4>Cookies</h4>
                        <p>Our site may use “cookies” to enhance and personalize your user experience. Cookies are generated by a your web browser for record-keeping purposes and to track information regarding your website navigation. Permission of Cookies can be modified through your own personal settings. You may choose to set your web browser to refuse cookies, or to alert you when cookies are being sent – however doing so may limit the functionalities of the site performance. Cookies are also be used for security purposes, website statistical data, pages visited, files downloaded, and user path.</p>
                        
                        <h4>Links to Other Websites</h4>
                        <p>In order to provide additional information or services, Technocrat Monk may include links to external websites. Clicking on such a link will navigate you away from Technocrat monk’s site. Other site’s privacy practices may differ from our own. We do not endorse or make any representations regarding third-party websites. When clicking off the Technocrat Monk site, we strongly encourage you to visit the other site’s Privacy Policy to ensure it meets the standards of your own personal preferences.</p>

<h4>Compliance with the Children’s Online Privacy Protection Act</h4>
<p>Protecting the privacy of children is important. The content of this site is not intended to attract or engage any individuals under the age of 13. For that reason, we never collect or maintain information at our site from those we under the age of 13.</p>

<h4>Your Information, Your Choices</h4>
<p>If you choose to no longer receive email notifications from Technocrat Monk, you are free at any time to unsubscribe in order to cease from receiving these types of notifications. If you have provided us with your information, you may request to update, modify or delete as deemed necessary by contacting us.</p>

<h4>Changes to this privacy policy</h4>
<p>Technocrat Monk retains the right to update this Privacy Policy at our discretion at any time. For benefit of your open awareness and knowledge, we make every effort to notify users of policy changes. Prior versions of this policy are retained for records. We encourage our users to frequently check this page for any possible changes to stay informed on how we protect your personal information.</p>

<h4>Your Acceptance of These Terms</h4>
<p>By using this site, you signify your acceptance of this policy. If you do not agree to this policy, please do not use our site. Your continued use of the site now or following the posting of changes to this policy will be deemed as your acceptance to the site and any changes.</p>

<h4>Contacting us</h4>
<p>If you have any questions regarding our Privacy Policy, the practices of this site, or your dealings withtechnocratmonk.com, please contact through our Contact Form, or with the following information:</p>
                        
<h2>Technocrat Monk</h2>
<p>Call: +91-7428022946<br/>

F-15, Second Floor, Okhla, Phase -1<br/>

New Delhi, 110020   </p>                
                    </div>
                </div>
            </div>

            {/* <AppDownloadStyle2 /> */}
 
            <FooterStyleOne />
        </>
    )
}

export default PrivacyPolicy;